feat(useClipboard): added a new composable
pikax/vue-composable pull request #709
Opened 2020-12-26 12:40 UTC by Eyoatam

2020-12-27 09:04 UTC, pikax requested changes
Just that change, thank you 👍

2020-12-27 09:04 UTC, pikax commented on docs/composable/web/clipboard.md
> +<clipboard-example/>
```suggestion
<ClientOnly>
  <clipboard-example/>
</ClientOnly>
```

This will make the PR to pass

2020-12-27 13:46 UTC, pikax commented
I'm failing to get the docs example working on my local environment, I will get in it working in the mean time.

Thank you

2020-12-27 14:49 UTC, Eyoatam commented
> I'm failing to get the docs example working on my local environment, I will get in it working in the mean time.
> 
> Thank you

cool 👍🏼

2021-01-01 11:20 UTC, pikax commented
> It wasn't working on my local environment either, I Think the problem is the package hasn't been updated 🤔

The reason was you were missing the export on the `index.ts`  


Made a few changes to the API to be a bit more understandable and also added the automatic get of the the clipboard on `focus`

2021-01-01 11:42 UTC, merged

2021-01-01 11:42 UTC, pikax commented
Thank you for the PR 👍